### ISSUE TITLE
Create PyPI accounts

### ISSUE THREAD

**Issue by rudymatela** [Moffran/calibrated_explanations#5]
I have uploaded the calibrated-explanations package on the test-PyPI index.  You can see it in the link below:

* https://test.pypi.org/project/calibrated-explanations/

I was automatically listed as the maintainer, but I think it makes sense that @Moffran and/or @tuvelofstrom are listed as well.  If you create your accounts I can add you as maintainers, just let me know through here or email.

You can create your accounts following the instructions in the [official packaging guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives) in the following two links:

* https://test.pypi.org/account/register/
* https://pypi.org/account/register/

This is __completely optional__ and can be done at any point in time, so there is no rush.  Take your time.  :smile:

Once you create your accounts, you'll be able to upload new releases yourselves if you like following the [calibrated-explanations release guide](https://github.com/Moffran/calibrated_explanations/blob/main/doc/release.md).

## TODO

* [x] create PyPI accounts for @rudymatela.  Done: [rudymatela (PyPI)](https://pypi.org/user/rudymatela/) and [rudymatela (test-PyPI)](https://test.pypi.org/user/rudymatela/)
* [x] create PyPI accounts for @Moffran 
* [x] create PyPI accounts for @tuvelofstrom

**Comment by tuvelofstrom** [comment]
accounts created and (partly) verified.
